import "./globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "@jmnuf",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", type: "image/svg+xml", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="relative flex max-h-[100vh] min-h-[100dvh] flex-col bg-fuchsia-900 text-violet-200">
        <div className="flex flex-col">{children}</div>
        <footer className="justify-content flex w-full flex-col items-center py-4 text-center text-sm text-slate-100">
          <p>
            &copy; 2023-{new Date().getFullYear()} jmnuf.app - All rights
            reserved
          </p>
        </footer>
      </body>
    </html>
  );
}
