import "./globals.css";

import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "@jmnuf",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", type: "image/svg+xml", url: "/favicon.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col min-h-[100dvh] max-h-[100vh] bg-fuchsia-900 text-violet-200">
				  <div className="flex flex-col">
					  {children}
					</div>
      </body>
    </html>
  );
}
